(function() {var implementors = {};
implementors['num'] = ["impl&lt;T: <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='num/complex/struct.Complex.html' title='num::complex::Complex'>Complex</a>&lt;T&gt;",];implementors['immeta'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='immeta/struct.Dimensions.html' title='immeta::Dimensions'>Dimensions</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='immeta/common/riff/struct.ChunkId.html' title='immeta::common::riff::ChunkId'>ChunkId</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='immeta/formats/png/enum.ColorType.html' title='immeta::formats::png::ColorType'>ColorType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='immeta/formats/png/enum.CompressionMethod.html' title='immeta::formats::png::CompressionMethod'>CompressionMethod</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='immeta/formats/png/enum.FilterMethod.html' title='immeta::formats::png::FilterMethod'>FilterMethod</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='immeta/formats/png/enum.InterlaceMethod.html' title='immeta::formats::png::InterlaceMethod'>InterlaceMethod</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='immeta/formats/gif/enum.Version.html' title='immeta::formats::gif::Version'>Version</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='immeta/formats/gif/enum.DisposalMethod.html' title='immeta::formats::gif::DisposalMethod'>DisposalMethod</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
